# We use YAML anchors to reduce duplication, with the simplifying assumption
# that all the jobs are really identical.
job-template: &job-template
  plan:
    - get: project-x.git
      trigger: true
    - task: t1
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: alpine}
        run:
          path: echo
          args: ["Hello, world!"]


###############################################################################

resources:

- name: project-x.git
  type: git
  source:
    uri: https://github.com/marco-m/concourse-pipelines.git
    branch: master

###############################################################################

jobs:

- name: j1
  <<: *job-template
- name: j2
  <<: *job-template
- name: j3
  <<: *job-template
- name: j4
  <<: *job-template
- name: j5
  <<: *job-template
