###############################################################################

resource_types:

- name: docker-image
  privileged: true
  type: docker-image
  source:
    repository: concourse/docker-image-resource

###############################################################################

resources:

# This git resource represents the source code we want to build.
- name: banana.git
  type: git
  source:
    uri: https://github.com/marco-m/concourse-pipelines.git
    # Normally the `paths` entry is not needed; we use it because this repo
    # contains multiple, unrelated, pipelines.
    paths: [build-docker-image]
    # Avoid triggering due to a change in the Docker images.
    ignore_paths:
    - build-docker-image/ci/build-img
    - build-docker-image/ci/test-img
    branch: ((branch))

# This git resource represents a Docker image needed by this pipeline.
- name: banana-build-img.git
  type: git
  source:
    uri: https://github.com/marco-m/concourse-pipelines.git
    # Trigger only due to a change to the Docker image.
    paths: [build-docker-image/ci/build-img]
    branch: ((branch))

# This git resource represents a Docker image needed by this pipeline.
- name: banana-test-img.git
  type: git
  source:
    uri: https://github.com/marco-m/concourse-pipelines.git
    # Trigger only due to a change to the Docker image.
    paths: [build-docker-image/ci/test-img]
    branch: ((branch))

- name: banana-build-img.docker
  type: docker-image
  source:
    repository: marcomm/banana-scratch-build
    username: ((dockerhub-username))
    password: ((dockerhub-password))

- name: banana-test-img.docker
  type: docker-image
  source:
    repository: marcomm/banana-scratch-test
    username: ((dockerhub-username))
    password: ((dockerhub-password))

###############################################################################

jobs:

- name: work-img
  serial_groups: [imgs]
  plan:

  - get: banana-build-img.git
    trigger: true
  - put: banana-build-img.docker
    get_params: {skip_download: true}
    params:
      build: banana-build-img.git/build-docker-image/ci/build-img
      # We abuse the `tag_file` here to contain the static string `latest`.
      # Together with `tag_prefix: ((branch))-`, it generates an image tag of
      # the from `((branch))-latest`. This means that each new `put` of a given
      # feature branch pipeline will override the previous image.
      tag_prefix: ((branch))-
      tag_file: banana-build-img.git/build-docker-image/ci/build-img/tag_file

  - get: banana-test-img.git
    trigger: true
  - put: banana-test-img.docker
    get_params: {skip_download: true}
    params:
      build: banana-test-img.git/build-docker-image/ci/test-img
      # We abuse the `tag_file` here to contain the static string `latest`.
      # Together with `tag_prefix: ((branch))-`, it generates an image tag of
      # the from `((branch))-latest`. This means that each new `put` of a given
      # feature branch pipeline will override the previous image.
      tag_prefix: ((branch))-
      tag_file: banana-test-img.git/build-docker-image/ci/test-img/tag_file
      # If on the other hand you want each `put` image not to overwrite the
      # previous one, then use the following two lines instead.
      #tag_prefix: ((branch))-
      #tag_file: banana-work-img-1.git/.git/short_ref

- name: build
  # The `serial_groups` is to avoid race conditions when a single commit
  # changes code both in banana-work-img-1.git and banana.git.
  serial_groups: [imgs]
  plan:
  - get: banana.git
    trigger: true
  - get: banana-build-img.docker
    trigger: true
    passed: [work-img]
  - task: build
    image: banana-build-img.docker
    file: banana.git/build-docker-image/ci/build-task.yml

# Although jobs `test-1` and `test-2` run in parallel and use the same docker
# image of job `build`, there is no need to specify the `serial_groups` because
# these jobs are already sequenced by the `passed [build]`.

- name: test-1
  plan:
  - get: banana.git
    trigger: true
    passed: [build]
  - get: banana-test-img.docker
    trigger: true
    passed: [work-img]
  - task: test
    image: banana-test-img.docker
    file: banana.git/build-docker-image/ci/test-1-task.yml

- name: test-2
  plan:
  - get: banana.git
    trigger: true
    passed: [build]
  - get: banana-test-img.docker
    trigger: true
    passed: [work-img]
  - task: test
    image: banana-test-img.docker
    file: banana.git/build-docker-image/ci/test-2-task.yml
