# This file is fan-in/ci/fan-in-02-pipeline.yml

repo: &repo
  uri: https://github.com/marco-m/concourse-pipelines.git
  branch: ((branch))

test-task-config: &test-task-config
  platform: linux
  image_resource:
    type: docker-image
    source: {repository: alpine}

resource_types:

- name: git
  type: docker-image
  source: {repository: concourse/git-resource}

resources:

- name: pear-A.git
  type: git
  source:
    <<: *repo
    paths:
    - fan-in/A
    - fan-in/ci

- name: pear-B.git
  type: git
  source:
    <<: *repo
    paths:
    - fan-in/B
    - fan-in/ci

jobs:

- name: test-A
  plan:
  - get: pear-A.git
    trigger: true
  - task: test-A
    config:
      <<: *test-task-config
      inputs:
      - {name: pear-A.git}
      run: {path: pear-A.git/fan-in/A/test-a.sh}

- name: test-B
  plan:
  - get: pear-B.git
    trigger: true
  - task: test-B
    config:
      <<: *test-task-config
      inputs:
      - {name: pear-B.git}
      run: {path: pear-B.git/fan-in/B/test-b.sh}
